### ISSUE TITLE
add setCloseOnButtonClick(boolean close)

### ISSUE THREAD

**Issue by piemmm** [vaadin/vaadin-confirm-dialog#120]
Aside from using my own buttons, it would be nice if there was a set method to disable the auto-close of the dialog when a confirm button is clicked.

I could use my own buttons, but that's a lot more bloat rather than simply setting a boolean

something like:
```java
setCloseOnButtonClick(boolean enabled);
```
 
There may be use-cases where you would also want this on the cancel button, though that may simply be a convenient abuse of how a dialog should work.

**Comment by javier-godoy** [comment]
Workaround in https://github.com/vaadin/vaadin-confirm-dialog/issues/117#issuecomment-775348565

**Comment by web-padawan** [comment]
Thanks @javier-godoy. This issue indeed appears to be a duplicate of #117, so let's discuss it there. Closing this issue.
