### ISSUE TITLE
It should be possible to create an alert style dialog

### ISSUE THREAD

**Issue by johannesh2** [vaadin/vaadin-confirm-dialog#2]
It should be possible to create an alert style confirm dialog with OK button

**Comment by samie** [comment]
Use case of this is is close to a Notification, although the dialog close button (if present) effectively gives two ways of closing the dialog they mean the same thing.

**Comment by manolo** [comment]
Just for reference this is an element I did based on vaadin-dialog.
https://github.com/manolo/crud-view/blob/master/elements/crud-confirm-dialog.html

**Comment by alvarezguille** [comment]
fixed by #11
