### ISSUE TITLE
Fix HTML demos

### ISSUE THREAD

**Issue by johannesh2** [vaadin/vaadin-confirm-dialog#22]
- Overall change the demos to behave like the Java demos, writes the confirm/reject/cancel event to status label.
- Change a few of the example titles
   - “Confirm Delete” → “Confirm or Cancel Dialog”
   - “Confirm or discard dialog example” → “Confirm‚ Reject or Cancel Dialog”
- Rename “Advanced Demos” tab to “Customization”
   - The button alignment is broken in Safari in the custom button example (iron-icon probably messing with the baseline)
       - Can be worked around with align-items: center; on the footer
- Lumo typography styles are not loaded
   - Should somehow be loaded inside the vaadin-demo-snippet scope
- Should remove the default top & bottom margin from the buttons (Lumo)
- Responsive styles missing (collapse the buttons to a single column below ~320px)

**Comment by jouni** [comment]
The two last items are not really demo issues. But I suppose that doesn’t mind you 😄

**Comment by johannesh2** [comment]
By accident there. I just copied without thinking that much. Can be fixed in this ticket
