### ISSUE TITLE
Lumo typography and color styles are not used for the dialog text content

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-confirm-dialog#32]
The typography styles should be inherited in normal apps into the dialog, if the developer has added the `lumo-typography` and `lumo-color` style modules in the same style scope as the dialog.

But in the examples, the demo-snippet component introduces a new shadow root which blocks the styles from being applied. The Lumo typography and color modules should somehow be loaded inside the vaadin-demo-snippet scope.

**Comment by anezthes** [comment]
I'm supposed to add my complaint here. Consider it done. :D Please fix! Huge pain in the ***.

**Comment by jouni** [comment]
This is essentially a duplicate of #106, just a more specific case.
