### ISSUE TITLE
Add Material theme support

### ISSUE THREAD

**Issue by johannesh2** [vaadin/vaadin-confirm-dialog#35]

**Comment by manolo** [comment]
Pls add it, needed for crud because it looks ugly

<img width="1052" alt="screen shot 2018-09-24 at 11 05 59" src="https://user-images.githubusercontent.com/161853/45944283-e3817f00-bfe9-11e8-8ec0-58c85ca0b9bb.png">

**Comment by manolo** [comment]
I think this is a beta blocker of 1.1.0 that should come with full featured material theme.
