### ISSUE TITLE
When a simple alert dialog is closed with `Esc` there no event to indicate that

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-confirm-dialog#41]
As a developer I want to receive an event whenever the Confirm Dialog is closed. Currently that is not the case: the default dialog with a single 'confirm' action can be closed by pressing the 'Esc' key without triggering any events:

```html
<vaadin-confirm-dialog>
  Please confirm that the patient is seated.
</vaadin-confirm-dialog>
<script>
  const dialog = document.querySelector('vaadin-confirm-dialog');
  dialog.addEventListener('cancel', e => console.log(e));
  dialog.addEventListener('confirm', e => console.log(e));
  dialog.addEventListener('reject', e => console.log(e));
  dialog.opened = true;
</script>
```

**Comment by TatuLund** [comment]
This is quite strange since I see in source code this one

https://github.com/vaadin/vaadin-confirm-dialog/blob/master/src/vaadin-confirm-dialog.html#L260

Which is a custom event defined here 

https://github.com/vaadin/vaadin-overlay/blob/master/src/vaadin-overlay.html#L555

What is going wrong ?

**Comment by vlukashov** [comment]
I've created a small demo to check if the issue is still there, and **I was not able to reproduce it** with the version 1.2.0: https://glitch.com/edit/#!/vaadin-confirm-dialog-event-on-cancel?path=index.js%3A9%3A0

Closing the issue.
