### ISSUE TITLE
Shouldn't close on Esc

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-confirm-dialog#62]
Despite having set `no-close-on-esc` in the wrapped `vaadin-dialog`, pressing <kbd>Esc</kbd> closes the dialog.

**Comment by jouni** [comment]
I’m trying to guess here, but I assume you are perhaps misusing a confirm dialog for some other purpose? 😃 

A standard confirm dialog should always be closable with the Esc key, so this issue could be considered “invalid”. But since it should be straightforward to let you do this (just bind the property), it should be alright to fix.

**Comment by heruan** [comment]
I won't say if your guess is correct or not 😈

But let's consider a proper confirm dialog, which is `cancelable` and `rejectable`: I would consider pressing <kbd>Esc</kbd> the same as pressing the button "Cancel", but if the dialog *isn't* `cancelable` it means I require an explicit choice: "Confirm" or "Reject", therefore in this case it must not close on pressing <kbd>Esc</kbd>.

**Comment by jouni** [comment]
Hmm, true, I skipped that for some reason completely. It seems we’ve skipped that use case completely in our initial design. Thanks for pointing it out :+1:

Would you have a good example of this kind of dialog?

**Comment by heruan** [comment]
To wrap it up (in my opinion, obviously):

- it should be possible to enable/disable "close on <kbd>ESC</kbd>" with an attribute (like in `vaadin-dialog`), whether or not the dialog is `cancelable`;

- when the dialog is closed by pressing <kbd>ESC</kbd>, a `cancel` event should be dispatched (as when pressing the "Cancel" button).

This way we can have a dialog which permits to cancel by pressing <kbd>ESC</kbd>, but also can force the user to explicitly press the "Cancel" button to close the dialog wihtout any choice; plus, the dialog can force the user to "Accept" or "Reject", as described by the discussed scenarios.
