### ISSUE TITLE
Focus ring should not be shown on touch devices

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-confirm-dialog#69]
After #57 got fixed, the focus-ring style is now visible on touch devices when the confirm dialog is opened. It shouldn’t, as it is purely visual noise for the user.

**Comment by jouni** [comment]
I’m willing to re-evaluate the necessity of forcing the focus-ring style on the focused confirm button.

**Comment by alvarezguille** [comment]
There was a discussion about this, IIRc focus ring was not added to the button when the focus wasn't gained by clicking or using tab.
Let's re-evaluate it.

**Comment by oluwasayo** [comment]
Could not reproduce on iPhone 7 and Samsung Galaxy S7. Please reopen if you manage to reproduce it on other touch devices.
