### ISSUE TITLE
Use case examples for frontend developers in vaadin.com

### ISSUE THREAD

**Issue by johannesh2** [vaadin/vaadin-confirm-dialog#7]
Use cases demos:
1. "Meeting starting" "Your next meeting starts in 5 minutes" "OK"
2. "Confirm delete" “Are you sure you want to delete the item?” “Delete” (should use error style), “Cancel”
3. "Publish" “Are you sure you want to publish the article?” “Publish” (should use primary style), “Cancel”
4. "Unsaved changes" ""Do you want to save or discard your changes before navigating away?"" "Save" (primary style), "Discard" (error style), "Cancel"

**Comment by samie** [comment]
These look good for specifying good defaults. Some old, but maybe inspiration for details from requested use cases: http://sami.app.fi/confirmdialog/
Especially note the following: 
- automatic resizing (with min/max/scroll) based on message content length
- "preformatting": keep newlines, but escape html for security (typically dialog shows user content), maybe markdown?
